spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    url: ${JDBC_URL:jdbc:mariadb://localhost:3306/credentialdb}
